// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Seirin.Persistence;

namespace Seirin.Persistence.Migrations
{
    [DbContext(typeof(DbContextSeirin))]
    [Migration("20181102182802_Init_UserV2")]
    partial class Init_UserV2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Seirin.Domain.Entities.mst_user", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("admin_create");

                    b.Property<DateTime>("admin_modify");

                    b.Property<int>("cnt_login_error");

                    b.Property<string>("code_cst");

                    b.Property<string>("create_by");

                    b.Property<DateTime>("create_date");

                    b.Property<int>("dest_flag");

                    b.Property<int>("display_order");

                    b.Property<string>("login_id");

                    b.Property<string>("login_pass");

                    b.Property<string>("loginkey");

                    b.Property<string>("mail");

                    b.Property<string>("modify_by");

                    b.Property<DateTime>("modify_date");

                    b.Property<string>("name");

                    b.Property<int>("use_flg");

                    b.HasKey("Id");

                    b.ToTable("Mst_Users");
                });
#pragma warning restore 612, 618
        }
    }
}
